GET http://localhost:3000/register
content-type: application/json

###
POST http://localhost:3000/login
content-type: application/json

{
    "username":"sufi",
    "password":"1234",
    

}

###
POST http://localhost:3000/login
content-type: application/json

{
    "username":"sufi",
    "password":"1234",
    "name":"sufi hamdi",
    "email":"ahmadhamdi2111@gmail.com"
